----사용자 관리----
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER ORACLE01 IDENTIFIED BY 1234;
GRANT CREATE SESSION TO ORACLE01;

SELECT * FROM ALL_USERS WHERE USERNAME='ORACLE01';
SELECT * FROM DBA_USERS WHERE USERNAME='ORACLE01';
SELECT * FROM DBA_OBJECTS WHERE OWNER='ORACLE01';

ALTER USER ORACLE01 IDENTIFIED BY 1212;
DROP USER ORACLE01;

--권한 관리--
CREATE USER ORACLE02 IDENTIFIED BY 1234;
GRANT RESOURCE, CREATE SESSION ,CREATE TABLE TO ORACLE02;

ALTER USER ORACLE02 QUOTA 2M ON USERS;

CREATE USER ORACLE03 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE VIEW TO ORACLE03;
ALTER USER ORACLE03 QUOTA 3M ON USERS;

REVOKE RESOURCE, CREATE VIEW FROM ORACLE03;

GRANT SELECT, INSERT ON SCOTT.TEMP002 TO ORACLE02;

--ORACLE03 계정에 SCOTT의 TEMP02 테이블에 CRUD 권한을 설정하라
GRANT INSERT,SELECT,UPDATE,DELETE ON SCOTT.TEMP002 TO ORACLE03;

CREATE ROLE ROLE_CRUD;
GRANT INSERT, SELECT, UPDATE, DELETE ON SCOTT.TEMP002 TO ROLE_CRUD;
GRANT ROLE_CRUD TO ORACLE02;


---15장 연습문제---
--SYSTEM 계정으로 접속하여 PREV_HW 계정을 생성,비밀번호는 ORCL,접속 권한을 부여
CREATE USER PREV_HW IDENTIFIED BY ORCL;
GRANT CREATE SESSION TO PREV_HW;

--. SCOTT 계정으로 접속하여 위에서 생성한 PREV_HW 계정에 SCOTT 소유의 EMP, DEPT,SALGRADE 테이블에 SELECT 권한을 부여

GRANT SELECT ON SCOTT.EMP TO PREV_HW;
GRANT SELECT ON SCOTT.DEPT TO PREV_HW;
GRANT SELECT ON SCOTT.SALGRADE TO PREV_HW;

--SCOTT 계정으로 접속하여 PREV_HW 계정에 SALGRADE 테이블의 SELECT 권한을 취소하는 SQL문을 작성
--권한의 변경이 완료되면 다음과 같이 PREV_HW 계정으로 SALGRADE 테이블의 조회여부를 확인
REVOKE SELECT ON SCOTT.SALGRADE FROM SALGRADE;
