SELECT * FROM EMP;
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;
---Oracle function---
SELECT * FROM professor;

SELECT NAME,UPPER(NAME),LOWER(NAME),POSITION,INITCAP(POSITION) FROM PROFESSOR;

---소문자로 다 변환하여 같은지 확인,구분없이 쉽게 찾을 수 있음---
SELECT * FROM PROFESSOR WHERE LOWER(NAME)='audie murphy';
---A가 들어간 이름 찾아내기,대문소자 상관없이 찾기위해 UPPER 또는 LOWER로 바꿔 찾기---
SELECT * FROM EMP WHERE UPPER(ENAME) LIKE UPPER('%a%');
---학생테이블에서 이름이 s로 끝나는 학생을 검색하라. 단, 검색할 때 대문자로 만들어서 검색한다.
SELECT * FROM STUDENT WHERE UPPER(NAME) LIKE UPPER('%s');

---문자열----
SELECT ENAME,LENGTH(ENAME),LENGTHB(ENAME) 
FROM EMP
WHERE LENGTH(ENAME)>5;

---한글인 경우---
SELECT LENGTH('홍길동'),LENGTHB('홍길동')
FROM DUAL;

---문자열 추출---
SELECT JOB,SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5)
FROM EMP;

SELECT TEL,SUBSTR(TEL,-4) FROM STUDENT; --- 음수를 넣으면 마지막부터 시작

---특정문자---
---INSTR(문자열,데이터위치,찾으려는 문자 몇번째 지정) :: 위치 찾기,문자열 추출할 때 사용--
SELECT TEL, INSTR(TEL,')')-1 FROM STUDENT;
SELECT EMAIL,INSTR(EMAIL,'@')-1 FROM PROFESSOR;
SELECT TEL,INSTR(TEL,')'),SUBSTR(TEL,1,INSTR(TEL,')')-1) FROM STUDENT;
SELECT * FROM EMP2;
SELECT NAME, SUBSTR(NAME,1,INSTR(NAME,' ')) 성,SUBSTR(NAME,INSTR(NAME,' ')+1) 이름 FROM EMP2;

-- REPLACE(문자열,찾는문자,대체문자) :: 문자 대체하기
SELECT * FROM STUDENT;
SELECT TEL,REPLACE(TEL,')','-') REPLACE1 FROM STUDENT;
SELECT TEL,REPLACE(TEL,')') REPLACE1 FROM STUDENT; --대체 문자 안넣으면 없애버림
SELECT REPLACE(TEL,SUBSTR(TEL,-4),'####') AS REPLACE1 FROM STUDENT;
SELECT TEL, REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,')')+1,3),'####') FROM STUDENT;

----가운데 번호 ####로 교체----
SELECT TEL,INSTR(TEL,')') FROM STUDENT; --)를 포함한 앞의 갯수 4,02일때 3
SELECT TEL,INSTR(TEL,'-') FROM STUDENT; -- -를 포함한 앞의 갯수 8,02일때 7
SELECT TEL, TEL,INSTR(TEL,'-') - (INSTR(TEL,')')+1) FROM STUDENT; 
SELECT TEL, SUBSTR(TEL,INSTR(TEL,')')+1,INSTR(TEL,'-') - (INSTR(TEL,')')+1)) FROM STUDENT;
SELECT TEL, REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,')')+1,INSTR(TEL,'-') - (INSTR(TEL,')')+1)),'####') TEL2 FROM STUDENT;

---빈공간 채우기---
SELECT 'Oracle',
LPAD('Oracle', 10, '#') AS LPAD_1,
RPAD('Oracle', 10, '*') AS RPAD_1,
LPAD('Oracle', 10) AS LPAD_2,
RPAD('Oracle', 10) AS RPAD_2
FROM DUAL;

SELECT JUMIN,RPAD(SUBSTR(JUMIN,1,7),13,'*') FROM STUDENT;

---마지막 번호를 #으로 바꾸고 채우기---
SELECT * FROM EMP2;
SELECT TEL,RPAD(SUBSTR(TEL,1,INSTR(TEL,'-')),12,'####') FROM EMP2;

---문자열 합치기----
SELECT CONCAT(EMPNO, ENAME), CONCAT(EMPNO, CONCAT(':',ENAME))
FROM EMP;
SELECT ENAME ||'-'||JOB ENAM_JOB FROM EMP; --||'합칠문자'||써도 가능,자주씀

SELECT TEL, SUBSTR(TEL,1,INSTR(TEL,')'))||'####-'||SUBSTR(TEL,-4) FROM STUDENT;

---공백지우기---
SELECT 
'[' || TRIM(' ORACLE ') || ']' AS TRIM,
'[' || TRIM(LEADING '-' FROM '--ORACLE--') || ']' AS TRIM_LEADING,
'[' || TRIM(TRAILING '-' FROM '--ORACLE--') || ']' AS TRIM_TRAILING,
'[' || TRIM(BOTH '-' FROM '--ORACLE--') || ']' AS TRIM_BOTH
FROM DUAL;

SELECT
'['||TRIM('-ORACLE-')||']'AS TRIM,
'['||LTRIM('-ORACLE-')||']'AS LTRIM,
'['||LTRIM('<-ORACLE->','<-')||']'AS LTRIM,
'['||RTRIM('-ORACLE-')||']'AS RTRIM,
'['||RTRIM('<-ORACLE->','->')||']'AS RTRIM
FROM DUAL;

SELECT 
ROUND(1234.5678) AS ROUND0,
ROUND(1234.5678,0) AS ROUND_0,
ROUND(1234.5678,-1) AS ROUND_MINUS1,
TRUNC(1234.5678,2) AS TRUNC_2,
TRUNC(1234.5678,-2) AS TRUNC_MINUS2
FROM DUAL;

SELECT 
CEIL(3.14), 
FLOOR(3.14), 
CEIL(-3.14), 
FLOOR(-3.14)
FROM DUAL;

-----날짜함수-----
SELECT 
SYSDATE AS NOW,
SYSDATE-1 AS YESTETDA,
SYSDATE+1 AS TOMORROW, 
ADD_MONTHS(SYSDATE,3)
FROM DUAL;

SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,3) REGULARDATE FROM EMP;
SELECT EMPNO,ENAME,HIREDATE,SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE,3840)>SYSDATE;

SELECT (SYSDATE -HIREDATE)/30 AS 근무연수 
FROM EMP;

SELECT EMPNO,ENAME,HIREDATE, 
ROUND(MONTHS_BETWEEN(HIREDATE,SYSDATE))근무월
FROM EMP 
WHERE ADD_MONTHS(HIREDATE,540)>SYSDATE;

----날짜의 반올림과 내림---
SELECT SYSDATE,
ROUND(SYSDATE,'CC') AS FORMAT_CC, --세기 기준으로 반올림
ROUND(SYSDATE,'YYYY') AS FORMAT_YYYY, -- 7월 기준으로 반올림
ROUND(SYSDATE,'Q') AS FORMAT_Q, --분기 중간 기준으로 반올림
ROUND(SYSDATE,'DDD') AS FORMAT_DD, --12시 기준으로 반올림
ROUND(SYSDATE,'HH') AS FORMAT_HH, -- 30분 기준으로 반올림
TRUNC(SYSDATE,'CC') AS FORMAT_CC,
TRUNC(SYSDATE,'YYYY') AS FORMAT_YYYY,
TRUNC(SYSDATE,'Q') AS FORMAT_Q,
TRUNC(SYSDATE,'DDD') AS FORMAT_DD,
TRUNC(SYSDATE,'HH') AS FORMAT_HH
FROM DUAL;

SELECT EMPNO,ENAME,EMPNO+'500','ABCD'||EMPNO
FROM EMP
WHERE ENAME = 'SMITH';

---형변환---
SELECT 
TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MM:SS') AS 현재날짜_시간
FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE, 'YYYY')AS YY,
TO_CHAR(SYSDATE, 'MM')AS MM,
TO_CHAR(SYSDATE, 'MON')AS MON,
TO_CHAR(SYSDATE, 'MONTH')AS MONTH,
TO_CHAR(SYSDATE, 'DD')AS DD,
TO_CHAR(SYSDATE, 'DY')AS DY,
TO_CHAR(SYSDATE, 'DAY')AS DAY
FROM DUAL;

---특정언어에 맞추어 날짜 출력--
SELECT SYSDATE,
TO_CHAR(SYSDATE,'MM')AS MM,
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=KOREAN')AS MON_KOR,
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=JAPANESE')AS MON_JPN,
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=ENGLISH')AS MON_ENG,
TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE=KOREAN')AS MONTH_KOR,
TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE=JAPANESE')AS MONTH_JPN,
TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE=ENGLISH')AS MONTH_ENG
FROM DUAL;

SELECT SAL,
TO_CHAR(SAL, '$999,999') AS SAL_$,
TO_CHAR(SAL, 'L999,999') AS SAL_L,
TO_CHAR(SAL, '999,999.00') AS SAL_1,
TO_CHAR(SAL, '000,999,999.00') AS SAL_2,
TO_CHAR(SAL, '000999999.99') AS SAL_3,
TO_CHAR(SAL, '999,999.00') AS SAL_4
FROM EMP;

--문자 데이터를 숫자 데이터로 변환--
SELECT TO_NUMBER('1,300', '999,999') -TO_NUMBER('1,500','999,999')
FROM DUAL;

SELECT TO_DATE('20230404','YYYY-MM-DD') AS DATEA
FROM DUAL;


---NULL 처리 함수
SELECT EMPNO,ENAME,SAL,COMM,SAL+COMM,NVL(COMM,0),SAL+NVL(COMM,0)
FROM EMP;

SELECT EMPNO, ENAME, SAL, COMM, 
SAL+COMM,
NVL2(COMM, 'O','X'), 
NVL2(COMM,SAL*12+COMM, SAL*12) AS ANNSAL 
FROM EMP;