SELECT *
FROM EMP,DEPT;
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMP.ENAME, EMP.SAL,EMP.DEPTNO,DEPT.DNAME,DEPT.LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.ENAME, E.SAL,E.DEPTNO,D.DNAME,D.LOC
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO;


--EMP2와 DEPT2를 조인 수행
--조인조건은 EMP2.DEPTNO=DEPT2.DECODE
--필드:이름,부서명,급여,
SELECT * FROM EMP2;
SELECT * FROM DEPT2;

SELECT E.NAME,D.DNAME,E.PAY,D.AREA
FROM EMP2 E,DEPT2 D
WHERE E.DEPTNO = D.DCODE;

--교수테이블과 학과 테이블을 조인하라, 조인조건: P.DEPTNO = D.DEPTNO 교수명 학과명 이메일
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT P.NAME,D.DNAME,P.EMAIL
FROM PROFESSOR P,DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO;

--학생의 이름,지도교수명 출력하라
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;

SELECT S.NAME,P.NAME
FROM STUDENT S,PROFESSOR P
WHERE S.DEPTNO1 =P.DEPTNO; 

SELECT E.ENAME,E.SAL,D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND SAL>=3000;

--학생이름,학과명,지도교수명
SELECT * FROM STUDENT;
SELECT * FROM  DEPARTMENT;
SELECT * FROM PROFESSOR;

SELECT S.NAME,D.DNAME,P.NAME
FROM STUDENT S,DEPARTMENT D,PROFESSOR P
WHERE S.DEPTNO1 = D.DEPTNO AND S.PROFNO = P.PROFNO;

--학생이름(NAME),학과명(DNAME), 점수(TOTAL)를 출력하라
SELECT * FROM SCORE;

SELECT S.NAME,D.DNAME,T.TOTAL
FROM STUDENT S,DEPARTMENT D,SCORE T
WHERE S.DEPTNO1 = D.DEPTNO AND S.STUDNO = T.STUDNO;

SELECT * FROM SALGRADE;
SELECT * FROM EMP;

SELECT ENAME,SAL,GRADE
FROM EMP E,SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT * FROM HAKJUM;

SELECT *
FROM STUDENT S,SCORE T,HAKJUM H;
--학생이름,점수,학점을 출력하라
SELECT S.NAME,T.TOTAL,H.GRADE 
FROM STUDENT S,SCORE T,HAKJUM H
WHERE S.STUDNO = T.STUDNO AND T.TOTAL BETWEEN H.MIN_POINT AND H.MAX_POINT;