SELECT *
FROM EMP,DEPT;
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMP.ENAME, EMP.SAL,EMP.DEPTNO,DEPT.DNAME,DEPT.LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.ENAME, E.SAL,E.DEPTNO,D.DNAME,D.LOC
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO;


--EMP2와 DEPT2를 조인 수행
--조인조건은 EMP2.DEPTNO=DEPT2.DECODE
--필드:이름,부서명,급여,
SELECT * FROM EMP2;
SELECT * FROM DEPT2;

SELECT E.NAME,D.DNAME,E.PAY,D.AREA
FROM EMP2 E,DEPT2 D
WHERE E.DEPTNO = D.DCODE;

--교수테이블과 학과 테이블을 조인하라, 조인조건: P.DEPTNO = D.DEPTNO 교수명 학과명 이메일
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT P.NAME,D.DNAME,P.EMAIL
FROM PROFESSOR P,DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO;

--학생의 이름,지도교수명 출력하라
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;

SELECT S.NAME,P.NAME
FROM STUDENT S,PROFESSOR P
WHERE S.DEPTNO1 =P.DEPTNO; 

SELECT E.ENAME,E.SAL,D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND SAL>=3000;

--학생이름,학과명,지도교수명
SELECT * FROM STUDENT;
SELECT * FROM  DEPARTMENT;
SELECT * FROM PROFESSOR;

SELECT S.NAME,D.DNAME,P.NAME
FROM STUDENT S,DEPARTMENT D,PROFESSOR P
WHERE S.DEPTNO1 = D.DEPTNO AND S.PROFNO = P.PROFNO;

--학생이름(NAME),학과명(DNAME), 점수(TOTAL)를 출력하라
SELECT * FROM SCORE;

SELECT S.NAME,D.DNAME,T.TOTAL
FROM STUDENT S,DEPARTMENT D,SCORE T
WHERE S.DEPTNO1 = D.DEPTNO AND S.STUDNO = T.STUDNO;

SELECT * FROM SALGRADE;
SELECT * FROM EMP;
--비등가 조인
SELECT ENAME,SAL,GRADE
FROM EMP E,SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT * FROM HAKJUM;

SELECT *
FROM STUDENT S,SCORE T,HAKJUM H;
--학생이름,점수,학점을 출력하라
SELECT S.NAME,T.TOTAL,H.GRADE 
FROM STUDENT S,SCORE T,HAKJUM H
WHERE S.STUDNO = T.STUDNO AND T.TOTAL BETWEEN H.MIN_POINT AND H.MAX_POINT;

----------------
select 필드 리스트
from 테이블명
where 행선택 조건
group by 그룹화 필드
order by 정렬기준 [ASC/DESC]

조인: 두개 이상의 테이블을 합치는 것
select 필드 리스트
from 테이블명1,테이블명2,...테이블n
where 조건1,조건n-1;

-----자체조인-----
SELECT * FROM EMP;

SELECT E1.ENAME 사원명, E2.ENAME
FROM EMP E1,EMP E2
WHERE E1.MGR =E2.EMPNO;

SELECT * FROM DEPT2;

SELECT D2.DNAME ,D1.DNAME
FROM DEPT2 D1,DEPT2 D2
WHERE D1.DCODE = D2.PDEPT;

SELECT * FROM EMP2;

SELECT PEMPNO,NAME,TEL
FROM EMP2;

SELECT EMPNO,NAME,TEL
FROM EMP2;

SELECT EMPNO,PEMPNO,NAME,TEL
FROM EMP2 E1,EMP E2;

//본인의 이름,상사의 이름,상사의 전화번호를 출력
SELECT E1.NAME 이름,E2.NAME 상사,E2.TEL
FROM EMP2 E1,EMP2 E2
WHERE E2.EMPNO = E1.PEMPNO;

-----외부 조인----
SELECT E1.ENAME,E2.ENAME
FROM EMP E1,EMP E2
WHERE E1.MGR =E2.EMPNO(+); -- LEFT OUT JOIN(왼쪽이 기준)

SELECT E.ENAME,D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO(+) =D.DEPTNO; -- RIGHT OUT JOIN(오른쪽이 기준)

SELECT E1.ENAME,E2.ENAME
FROM EMP E1,EMP E2
WHERE E1.MGR(+) =E2.EMPNO(+); --outer-join은 한테이블만 가능

SELECT * FROM STUDENT;

SELECT S.NAME,P.NAME
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO = P.PROFNO(+);

----SQL-99 표준 문법----
--NATURAL JOIN
SELECT ENAME,DNAME
FROM EMP E NATURAL JOIN DEPT D; -- COULMN명, 데이터 타입 모두 같은 경우

SELECT * FROM EMP2;
SELECT * FROM DEPT2;

SELECT NAME,DNAME
FROM EMP2 E NATURAL JOIN DEPT2 D; -- COULMN명이 달라서 안됨

--JOIN USING
SELECT ENAME,DNAME
FROM EMP E JOIN DEPT D
USING(DEPTNO);

--JOIN ON
SELECT NAME,DNAME
FROM EMP2 E JOIN DEPT2 D
ON(E.DEPTNO=D.DCODE);

SELECT S.NAME 학생이름, DNAME 학과명, P.NAME 지도교수명
FROM STUDENT S JOIN DEPARTMENT D ON(S.DEPTNO1 = D.DEPTNO)
JOIN PROFESSOR P ON (S.PROFNO = P.PROFNO);

---OUTER JOIN
SELECT S.NAME,P.NAME
FROM STUDENT S LEFT OUTER JOIN PROFESSOR P
ON (S.PROFNO = P.PROFNO);

SELECT S.NAME,P.NAME
FROM STUDENT S RIGHT OUTER JOIN PROFESSOR P
ON (S.PROFNO = P.PROFNO);

SELECT S.NAME,P.NAME
FROM STUDENT S FULL OUTER JOIN PROFESSOR P
ON (S.PROFNO = P.PROFNO);

SELECT * FROM EMP2;

SELECT E2.NAME 나 ,E1.NAME 상사
FROM EMP2 E1 LEFT OUTER JOIN EMP2 E2 ON (E1.EMPNO = E2.PEMPNO);

SELECT E2.NAME 나 ,E1.NAME 상사
FROM EMP2 E1 RIGHT OUTER JOIN EMP2 E2 ON (E1.EMPNO = E2.PEMPNO);

SELECT E2.NAME 나 ,E1.NAME 상사
FROM EMP2 E1 FULL OUTER JOIN EMP2 E2 ON (E1.EMPNO = E2.PEMPNO);