CREATE TABLE TEMP01(
COL1 VARCHAR2(10),
COL2 VARCHAR2(20));

INSERT INTO TEMP01 VALUES('USER1','TEST1');

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

SELECT * FROM SCOTT.TEMP002;
INSERT INTO SCOTT.TEMP002
VALUES ('AAA','BBB');
SELECT * FROM SCOTT.TEMP002;
UPDATE SCOTT.TEMP002 SET COL 02='4545' WHERE COL01='AAA';
DELETE FROM SCOTT.TEMP002 WHERE COL01='AAA';

SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;