CREATE TABLE TEMP01(
COL1 VARCHAR2(10),
COL2 VARCHAR2(20));

INSERT INTO TEMP01 VALUES('USER00','GRANT_TEST');
CREATE VIEW V_TEMP01
AS (SELECT * FROM TEMP01);
SELECT * FROM V_TEMP01;

--REVOKE로 권한을 제거 한 후--
CREATE VIEW V_TEMP02
AS (SELECT * FROM TEMP01);

CREATE TABLE TEMP02(
COL1 VARCHAR2(10),
COL2 VARCHAR2(20));
INSERT INTO TEMP02
VALUES ('AAA','BBB');

CREATE TABLE TEMP002
(COL1 VARCHAR2(10),
COL2 VARCHAR2(20));

SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;



