--PL/SQL
--EX) EMP테이블에서 변수에 사원번호를 입력한 후  사원의 사원번호와 이름을 조회해서 화면에 출력 
DECLARE
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
BEGIN
    SELECT EMPNO, ENAME INTO V_EMPNO, V_ENAME
    FROM EMP
    WHERE EMPNO =&EMPNO;
    DBMS_OUTPUT.PUT_LINE(V_EMPNO||' - THIS MEMBER''S NAME IS '||V_ENAME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO MEMBER!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('MORE THAN 2 MEMEBER !');
END;
/

CREATE TABLE T_PLSQL(
NO NUMBER,
NAME VARCHAR2(10),
TEL NUMBER);

BEGIN
INSERT INTO T_PLSQL VALUES(1,'AAA',1111);
END;
/

SELECT * FROM T_PLSQL;
COMMIT;

DECLARE
    V_NO NUMBER:=&NO;
    V_NAME VARCHAR2(10):='&NAME';
    V_TEL NUMBER:=&TEL;
BEGIN
    INSERT INTO T_PLSQL VALUES(V_NO,V_NAME,V_TEL);
END;
/

DECLARE
    V_NO NUMBER:=&NO;
    V_NAME VARCHAR2(10):='&NAME';
    
BEGIN
UPDATE T_PLSQL
SET NAME = V_NAME
WHERE NO = V_NO;
END;
/

DECLARE
    v_emp EMP%ROWTYPE;
BEGIN
    SELECT *
    INTO v_emp
    FROM EMP
    WHERE EMPNO = 7369;

    v_emp.SAL := v_emp.SAL * 1.1;

    DBMS_OUTPUT.PUT_LINE('이름: ' || v_emp.ENAME);
    DBMS_OUTPUT.PUT_LINE('인상급여: ' || v_emp.SAL);
END;
/

DECLARE
    V_NAME T_PLSQL.NAME%TYPE:='&NAME';
    V_NO T_PLSQL.NO%TYPE:=&NO;
    
BEGIN
UPDATE T_PLSQL
SET NAME = V_NAME
WHERE NO = V_NO;
END;
/

DECLARE
    V_NO NUMBER:=&NO;
    V_NAME VARCHAR2(10):='&NAME';
    V_TEL NUMBER:=&TEL;
BEGIN
    INSERT INTO T_PLSQL VALUES(V_NO,V_NAME,V_TEL);
END;
/

SELECT * FROM T_PLSQL;

BEGIN
DELETE FROM T_PLSQL
WHERE NO=3;
END;
/
SELECT * FROM STUDENT;

--DEPT TABLE 참조하여 새로운 테이블생성(TL_DEPT)
CREATE TABLE PL_DEPT AS
SELECT * FROM DEPT;

--1. STUDENT TABLE에서 학번을 입력하면 해당학생의 학번,이름,학과번호를 출력되도록한다
--출력형태: 학번 이름 학과번호
DECLARE
V_STUDNO STUDENT.STUDNO%TYPE;
V_NAME STUDENT.NAME%TYPE;
V_DEPTNO1 STUDENT.DEPTNO1%TYPE;
BEGIN
    SELECT STUDNO, NAME, DEPTNO1 INTO V_STUDNO, V_NAME, V_DEPTNO1
    FROM STUDENT
    WHERE STUDNO =&STUDNO;
    DBMS_OUTPUT.PUT_LINE(V_STUDNO||' '||V_NAME||' '||V_DEPTNO1);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO MEMBER!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('MORE THAN 2 MEMEBER !');
END;
/

--PL_DEPT테이블에 데이터를 입력하라(50 DATABASE BUSAN)
DECLARE
V_DEPTNO PL_DEPT.DEPTNO%TYPE:=&DEPTNO;
V_NAME PL_DEPT.DNAME%TYPE:='&DNAME';
V_LOC PL_DEPT.LOC%TYPE:='&LOC';
BEGIN
INSERT INTO PL_DEPT VALUES(V_DEPTNO,V_NAME,V_LOC);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO MEMBER!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('MORE THAN 2 MEMEBER !');
END;
/
--3. 부서번호에 따른 LOC를 수정하는 PLSQL을 작성해라
DECLARE
V_DEPTNO PL_DEPT.DEPTNO%TYPE;
V_LOC PL_DEPT.LOC%TYPE;
BEGIN
    UPDATE PL_DEPT
    SET LOC = '&LOC'
    WHERE DEPTNO = &DEPTNO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO MEMBER!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('MORE THAN 2 MEMEBER !');
END;
/

--4. 부서번호를 입력받아 해당 데이터를 삭제하는 PLSQL를 작성해라
DECLARE
V_DEPTNO PL_DEPT.DEPTNO%TYPE;
BEGIN
    DELETE FROM PL_DEPT
    WHERE DEPTNO = &DEPTNO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO MEMBER!');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('MORE THAN 2 MEMEBER !');
END;
/

SELECT * FROM PL_DEPT;

--MERGE

CREATE TABLE T_MERGE1(
NO NUMBER,
FRUIT VARCHAR2(10));

CREATE TABLE T_MERGE2
AS SELECT * FROM T_MERGE1;

INSERT INTO T_MERGE1 VALUES(1,'APPLE');
INSERT INTO T_MERGE1 VALUES(2,'BANANA');
INSERT INTO T_MERGE1 VALUES(3,'ABCD');

INSERT INTO T_MERGE2 VALUES(1,'CHERRY');
INSERT INTO T_MERGE2 VALUES(2,'MELON');
INSERT INTO T_MERGE2 VALUES(4,'KKKK');

COMMIT;

SELECT * FROM T_MERGE1;
SELECT * FROM T_MERGE2;

BEGIN
MERGE INTO T_MERGE2 T2
USING T_MERGE1 T1
ON(T1.NO = T2.NO)
WHEN MATCHED THEN
    UPDATE SET
    T2.FRUIT = T1.FRUIT
WHEN NOT MATCHED THEN
    INSERT VALUES(T1.NO,T1.FRUIT);
END;
/

SELECT * FROM T_MERGE2;

----실습
--1.부서 테이블 내용 그대로 복사하여 테이블 생성 T_DEPT100
CREATE TABLE T_DEPT100
AS SELECT * FROM DEPT

--2. 부서 테이블의 구조만 복사한 테이블 생성 T_DEPT101
CREATE TABLE T_DEPT101
AS SELECT * FROM DEPT WHERE 1<>1;

--3.T_DEPT101테이블에 다음 내용 추가
--30 DATABASE부산,40PROGRAM 서울,50 AI 서울
INSERT INTO T_DEPT101 VALUES(30,'DATABASE','BUSAN');
INSERT INTO T_DEPT101 VALUES(40,'PROGRAM','SEOUL');
INSERT INTO T_DEPT101 VALUES(50,'AI','SEOUL');
SELECT * FROM T_DEPT100;
--4.T_DEPT100테이블에 T_DEPT101테이블을 MERGE하라
--병합 조건 DEPTNO를 사용, MATCH되면 DANME,LOC를 업데이트 MATCH 되지 않을 시 레코드 추가
BEGIN
MERGE INTO T_DEPT100 TD100
USING T_DEPT101 TD101
ON(TD101.DEPTNO = TD100.DEPTNO)
WHEN MATCHED THEN
    UPDATE SET
    TD100.DNAME = TD101.DNAME,
    TD100.LOC = TD101.LOC
WHEN NOT MATCHED THEN
    INSERT VALUES(TD101.DEPTNO,TD101.DNAME,TD101.LOC);
END;
/
SELECT * FROM T_DEPT100;


---
CREATE TABLE PL_EMP
AS SELECT EMPNO,ENAME,SAL FROM EMP;

SELECT * FROM PL_EMP;

DECLARE
VNO PL_EMP.EMPNO%TYPE;
VNAME PL_EMP.ENAME%TYPE;
VSAL PL_EMP.SAL%TYPE;
BEGIN
    SELECT EMPNO,ENAME,SAL INTO VNO,VNAME,VSAL
    FROM PL_EMP
    WHERE EMPNO=&EMPNO;
    DBMS_OUTPUT.PUT_LINE(VNO||' '||VNAME||' '||VSAL);
END;
/

DECLARE
    V_ROW PL_EMP%ROWTYPE;
BEGIN
    SELECT * INTO V_ROW
    FROM PL_EMP
    WHERE EMPNO=&EMPNO;
    DBMS_OUTPUT.PUT_LINE(V_ROW.EMPNO||' '||V_ROW.ENAME||' '||V_ROW.SAL);
END;
/

--RECODE TYPE변수
DECLARE
TYPE EMP_RECORD_TYPE IS RECORD(
    V_NO EMP.EMPNO%TYPE,
    V_NAME EMP.ENAME%TYPE,
    V_SAL EMP.SAL%TYPE
);

V_RECORD EMP_RECORD_TYPE;

BEGIN
    SELECT EMPNO,ENAME,SAL INTO V_RECORD
    FROM EMP
    WHERE EMPNO = &EMPNO;
    DBMS_OUTPUT.PUT_LINE(V_RECORD.V_NO||' '||V_RECORD.V_NAME||' '||V_RECORD.V_SAL);
END;
/
select * from student;

--학생테이블에서 학생 이름, 키, 몸무게를 출력하는 plsql을 변수의 type을 recorde + table으로 작성해라
DECLARE
    TYPE V_STUD_REC IS RECORD(
        V_STUNO   STUDENT.STUDNO%TYPE,
        V_NAME    STUDENT.NAME%TYPE,
        V_HEIGHT  STUDENT.HEIGHT%TYPE,
        V_WEIGHT  STUDENT.WEIGHT%TYPE
    );

    TYPE V_STUD_TAB IS TABLE OF V_STUD_REC INDEX BY PLS_INTEGER;

    V_RECORD   V_STUD_REC;
    V_STUD_TAB V_STUD_TAB;
    i          PLS_INTEGER := 0;
BEGIN
    -- 단일 학생 조회
    SELECT STUDNO, NAME, HEIGHT, WEIGHT
    INTO V_RECORD.V_STUNO, V_RECORD.V_NAME, V_RECORD.V_HEIGHT, V_RECORD.V_WEIGHT
    FROM STUDENT
    WHERE STUDNO = &STUDNO;

    DBMS_OUTPUT.PUT_LINE('단일 조회: ' ||
        V_RECORD.V_STUNO || ' ' ||
        V_RECORD.V_NAME || ' ' ||
        V_RECORD.V_HEIGHT || ' ' ||
        V_RECORD.V_WEIGHT);

    -- 전체 학생 조회 후 배열에 저장
    FOR STUD_ROW IN (SELECT STUDNO, NAME, HEIGHT, WEIGHT FROM STUDENT) LOOP
        i := i + 1;
        V_STUD_TAB(i).V_STUNO  := STUD_ROW.STUDNO;
        V_STUD_TAB(i).V_NAME   := STUD_ROW.NAME;
        V_STUD_TAB(i).V_HEIGHT := STUD_ROW.HEIGHT;
        V_STUD_TAB(i).V_WEIGHT := STUD_ROW.WEIGHT;
    END LOOP;

    -- 배열 출력
    FOR j IN 1 .. i LOOP
        DBMS_OUTPUT.PUT_LINE(
            V_STUD_TAB(j).V_STUNO || ' ' ||
            V_STUD_TAB(j).V_NAME || ' ' ||
            V_STUD_TAB(j).V_HEIGHT || ' ' ||
            V_STUD_TAB(j).V_WEIGHT
        );
    END LOOP;
END;
/

--TABLE TYPE변수
DECLARE
    T_NAME EMP.ENAME%TYPE;
    TYPE E_TABLE_TYPE IS TABLE OF
    EMP.ENAME%TYPE
    INDEX BY BINARY_INTEGER;
    V_NAME E_TABLE_TYPE;
BEGIN
    SELECT ENAME INTO T_NAME
    FROM EMP
    WHERE EMPNO=&EMPNO;
    V_NAME(0):=T_NAME;
    DBMS_OUTPUT.PUT_LINE(V_NAME(0));
END;
/
DECLARE
    TYPE E_TABLE_TYPE IS TABLE OF
    EMP.ENAME%TYPE
    INDEX BY BINARY_INTEGER;
    TAB_TYPE E_TABLE_TYPE;
    A BINARY_INTEGER :=0;
BEGIN
    FOR I IN (SELECT ENAME FROM EMP) LOOP
    A:=A+1;
    TAB_TYPE(A):=I.ENAME;
    END LOOP;
    FOR J IN 1..A LOOP
        DBMS_OUTPUT.PUT_LINE(TAB_TYPE(J));
    END LOOP;
END;
/

--조건 제어문 (IF-THEN-ELSE)
DECLARE
    v_ename EMP.ENAME%TYPE;
    v_sal EMP.SAL%TYPE;
BEGIN
    SELECT ENAME, SAL
    INTO v_ename, v_sal
    FROM EMP
    WHERE EMPNO = &EMPNO;
IF v_sal>= 3000 THEN
    DBMS_OUTPUT.PUT_LINE(v_ename|| ' : 고급여');
ELSE
    DBMS_OUTPUT.PUT_LINE(v_ename|| ' : 일반급여');
END IF;
END;
--CASE문
DECLARE
    v_ename EMP.ENAME%TYPE;
    v_sal EMP.SAL%TYPE;
    v_tax NUMBER;
BEGIN
    SELECT ENAME, SAL
    INTO v_ename, v_sal
    FROM EMP
    WHERE EMPNO = &empno;
CASE
    WHEN v_sal>= 3000 THEN v_tax:= v_sal* 0.2;   
    WHEN v_sal>= 2000 THEN v_tax:= v_sal* 0.15; 
    WHEN v_sal>= 1000 THEN v_tax:= v_sal* 0.1;   
    ELSE v_tax:= v_sal* 0.05;                    
END CASE;
    DBMS_OUTPUT.PUT_LINE('사원명: ' || v_ename);
    DBMS_OUTPUT.PUT_LINE('급여: ' || v_sal);
    DBMS_OUTPUT.PUT_LINE('세금: ' || v_tax);
END;
/

-- 반복제어문(LOOP)
DECLARE
    v_empno NUMBER := 7369;
    v_cnt NUMBER;
BEGIN
    LOOP
        SELECT COUNT(*)
        INTO v_cnt
        FROM EMP
        WHERE EMPNO = v_empno;
        IF v_cnt> 0 THEN
        DBMS_OUTPUT.PUT_LINE(v_empno|| ' : 존재');
        ELSE
        DBMS_OUTPUT.PUT_LINE(v_empno|| ' : 없음');
        END IF;
        v_empno:= v_empno+ 1;
        EXIT WHEN v_empno> 7373;
     END LOOP;
END;
/
--WHILE LOOP
DECLARE
        v_empno NUMBER := 7369;
        v_cnt NUMBER;
    BEGIN
    WHILE v_empno<= 7373 LOOP
        SELECT COUNT(*)
        INTO v_cnt
        FROM EMP
        WHERE EMPNO = v_empno;
        IF v_cnt> 0 THEN
        DBMS_OUTPUT.PUT_LINE(v_empno|| ' : 존재');
        ELSE
        DBMS_OUTPUT.PUT_LINE(v_empno|| ' : 없음');
        END IF;
        v_empno:= v_empno+ 1;
    END LOOP;
END;

--CONTINUE WHEN
