SELECT * FROM EMP;
SELECT * FROM EMP2;
SELECT * FROM DEPT;
SELECT * FROM DEPT2;
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;

--JONES보다 더 높은 돈을 받는 사람
SELECT ENAME,SAL
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME='JONES');
             
SELECT ENAME,SAL
FROM EMP
WHERE SAL > (SELECT AVG(SAL)
             FROM EMP);
             
--JOIN과 서브쿼리
SELECT E.EMPNO,E.ENAME,E.JOB,E.SAL,D.DNAME,D.LOC
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO = 20 AND SAL>(SELECT AVG(SAL) FROM EMP);

SELECT NAME,DNAME,HEIGHT 
FROM STUDENT S JOIN DEPARTMENT D ON (S.DEPTNO1 = D.DEPTNO)
AND HEIGHT < (SELECT AVG(HEIGHT) FROM STUDENT);

SELECT * FROM STUDENT;

--교수 테이블에서 정교수(A FULL PROFESSOR) 평균급여보다 높은 급여를 받는 교수의 
--이름,학과,급여를 출력하라
SELECT * FROM PROFESSOR;

SELECT NAME,DNAME,PAY
FROM PROFESSOR P JOIN DEPARTMENT D ON (D.DEPTNO = P.DEPTNO)
WHERE PAY > (SELECT AVG(PAY)
             FROM PROFESSOR
             WHERE POSITION = 'a full professor');
             
-- 10 부서의 급여의 평균보다 높은 급여를 받는 직원의 이름,부서,직책,급여를 출력해라
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT E.ENAME,D.DNAME,E.JOB,E.SAL
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL > (SELECT AVG(SAL)
             FROM EMP
             WHERE DEPTNO = 10);
             
--다중행 서브쿼리 IN
--그룹별 가장 높은 급여의 이름,급여,부서 출력
SELECT ENAME,SAL,DEPTNO
FROM EMP
WHERE SAL IN(SELECT MAX(SAL)FROM EMP GROUP BY DEPTNO);

--학과별 키가 가장 큰 학생의 이름과, 학과명, 키를 출력
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;

SELECT NAME,DNAME,HEIGHT
FROM STUDENT S JOIN DEPARTMENT D ON (S.DEPTNO1 = D.DEPTNO)
WHERE HEIGHT IN (SELECT MAX(HEIGHT)
                 FROM STUDENT
                 GROUP BY DEPTNO1);
                 
--직책별 급여가 가장 높은 사람의 이름,직책,급여를 출력 
SELECT ENAME,JOB,SAL
FROM EMP
WHERE SAL IN(SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO);

-----ANY,SOME-----
SELECT * 
FROM EMP
WHERE SAL = ANY(SELECT MAX(SAL)FROM EMP GROUP BY DEPTNO);

SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO; --3000 2850 5000

SELECT * FROM EMP WHERE SAL > ANY(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
SELECT * FROM EMP WHERE SAL < ANY(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP WHERE SAL > SOME(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
SELECT * FROM EMP WHERE SAL < SOME(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

---ALL---
SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO; --2258 1566 2916
SELECT * FROM EMP WHERE SAL > ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY ENAME;
SELECT * FROM EMP WHERE SAL < ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY ENAME;

--30번 부서사원들의 최대급여 보다 적은급여를 받는 사원정보를 ANY 연산자로 출력하기
select *
from emp
where sal < any(select max(sal) from emp where deptno = 30);

---EXISTS
-- SUBQUERY 결과가하나이상존재하는경우
SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO=10);
-- SUBQUERY 결과가존재하지않는경우
SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO=50);

----다중열 서브쿼리----
SELECT EMPNO,DEPTNO,SAL
FROM EMP
WHERE (DEPTNO,SAL) IN (SELECT DEPTNO,MAX(SAL)
                       FROM EMP
                       GROUP BY DEPTNO);
                       
--학과별 점수가 가장 높은 사람의 이름,학과명,점수,학점을 출력
SELECT * FROM STUDENT;
SELECT * FROM SCORE;
SELECT * FROM DEPARTMENT;
SELECT * FROM HAKJUM;

SELECT S.NAME 이름,D.DNAME 학과명,S2.TOTAL 점수,H.GRADE 학점
FROM STUDENT S JOIN DEPARTMENT D ON (S.DEPTNO1 = D.DEPTNO) 
     JOIN SCORE S2 ON(S2.STUDNO = S.STUDNO)
     JOIN HAKJUM H ON(S2.TOTAL BETWEEN MIN_POINT AND MAX_POINT)
     WHERE (S.DEPTNO1,TOTAL) IN (SELECT DEPTNO1,MAX(TOTAL)
                             FROM STUDENT S ,SCORE S2
                             WHERE S.STUDNO=S2.STUDNO
                             GROUP BY S.DEPTNO1
                             );
                             
                             