-----7장-----
SELECT * FROM EMP;
--1번
SELECT DEPTNO,ROUND(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP
GROUP BY DEPTNO
ORDER BY COUNT(DEPTNO);

--2번
SELECT JOB,COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*)>=3;

--3번
SELECT TO_CHAR(HIREDATE,'YYYY') HIRE_YEAR,DEPTNO,COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;

--4번
SELECT NVL2(COMM,'O','X') EXIST_COMM,COUNT(*) CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');

--5번
SELECT DEPTNO,TO_CHAR(HIREDATE,'YYYY') HIRE_YEAR,COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL)
FROM EMP
GROUP BY ROLLUP(DEPTNO,TO_CHAR(HIREDATE,'YYYY'))
ORDER BY DEPTNO;

--학생테이블 지역별, 전공1별 인원수 구하기--
SELECT *
FROM STUDENT;

SELECT DEPTNO1 전공1,SUBSTR(TEL,1,INSTR(TEL,')')-1) 광역시도,COUNT(*) CNT
FROM STUDENT
GROUP BY SUBSTR(TEL,1,INSTR(TEL,')')-1),DEPTNO1
ORDER BY DEPTNO1;

-----8장-----
SELECT * FROM EMP;
SELECT * FROM DEPT;
--1번)급여(SAL)가 2000 초과인 사원들의 부서 정보, 사원 정보를 오른쪽과 같이 출력해 보세요
--99이전
SELECT E.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL>=2000
ORDER BY E.DEPTNO;

--99이후
SELECT DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL
FROM EMP E NATURAL JOIN DEPT D
WHERE SAL>=2000
ORDER BY DEPTNO;

--2번)오른쪽과 같이 각 부서별 평균 급여, 최대 급여, 최소 급여, 사원수를 출력해 보세요.
--99이전
SELECT E.DEPTNO,D.DNAME,ROUND(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO,D.DNAME
ORDER BY E.DEPTNO;

--99이후
SELECT DEPTNO,D.DNAME,ROUND(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP E  NATURAL JOIN DEPT D 
GROUP BY DEPTNO,DNAME
ORDER BY DEPTNO;

--3번)모든 부서 정보와 사원 정보를 오른쪽과 같이 부서 번호, 사원 이름순으로 정렬하여 출력해 보세요.
--99이전
SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.JOB,E.SAL
FROM EMP E,DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY E.DEPTNO,E.ENAME;

--99이후
SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.JOB,E.SAL
FROM EMP E LEFT OUTER JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
ORDER BY E.DEPTNO,E.ENAME;

--4번
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
--99이전
SELECT D.DEPTNO, D.DNAME,E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO, 
       S.LOSAL,S.HISAL, S.GRADE,E2.MGR MGR_EMPNO, E2.MGR MGR_ENAME
FROM EMP E1,EMP E2,DEPT D,SALGRADE S
WHERE E1.MGR = E2.EMPNO(+) 
      AND D.DEPTNO=E1.DEPTNO(+)
      AND E1.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO,E1.ENAME;

--99이후
SELECT D.DEPTNO, D.DNAME,E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO, 
       S.LOSAL,S.HISAL, S.GRADE,E2.MGR MGR_EMPNO, E2.MGR MGR_ENAME
FROM  EMP E1 RIGHT OUTER JOIN DEPT D ON(E1.DEPTNO = D.DEPTNO)
      LEFT OUTER JOIN EMP E2 ON(E1.MGR=E2.EMPNO)
      LEFT OUTER JOIN SALGRADE S ON(E1.SAL BETWEEN S.LOSAL AND S.HISAL)
ORDER BY D.DEPTNO,E1.ENAME;

--학생명,지도교수명,성적,학점을 출력하라
--학생정보 중 지도교수가 없는 학생이 출력되도록
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;
SELECT * FROM HAKJUM;
SELECT * FROM SCORE;

SELECT S.NAME 학생이름,P.NAME 교수명 ,J.TOTAL 점수,H.GRADE 학점
FROM STUDENT S ,PROFESSOR P,HAKJUM H,SCORE J
WHERE S.PROFNO= P.PROFNO(+) 
  AND S.STUDNO = J.STUDNO(+)
  AND J.TOTAL BETWEEN MIN_POINT(+) AND MAX_POINT(+);
  
SELECT S.NAME 학생이름,P.NAME 교수명 ,J.TOTAL 점수,H.GRADE 학점
FROM STUDENT S LEFT OUTER JOIN PROFESSOR P ON (S.PROFNO = P.PROFNO)
LEFT OUTER JOIN SCORE J ON (S.STUDNO = J.STUDNO)
LEFT OUTER JOIN HAKJUM H ON (J.TOTAL BETWEEN H.MIN_POINT AND H.MAX_POINT);