-----7장-----
SELECT * FROM EMP;
--1번
SELECT DEPTNO,ROUND(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP
GROUP BY DEPTNO
ORDER BY COUNT(DEPTNO);

--2번
SELECT JOB,COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*)>=3;

--3번
SELECT TO_CHAR(HIREDATE,'YYYY') HIRE_YEAR,DEPTNO,COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;

--4번
SELECT NVL2(COMM,'O','X') EXIST_COMM,COUNT(*) CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');

--5번
SELECT DEPTNO,TO_CHAR(HIREDATE,'YYYY') HIRE_YEAR,COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL)
FROM EMP
GROUP BY ROLLUP(DEPTNO,TO_CHAR(HIREDATE,'YYYY'))
ORDER BY DEPTNO;

--학생테이블 지역별, 전공1별 인원수 구하기--
SELECT *
FROM STUDENT;

SELECT DEPTNO1 전공1,SUBSTR(TEL,1,INSTR(TEL,')')-1) 광역시도,COUNT(*) CNT
FROM STUDENT
GROUP BY SUBSTR(TEL,1,INSTR(TEL,')')-1),DEPTNO1
ORDER BY DEPTNO1;

-----8장-----
SELECT * FROM EMP;
SELECT * FROM DEPT;
--1번
SELECT E.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL>=2000
ORDER BY E.DEPTNO;

--2번
SELECT E.DEPTNO,D.DNAME,ROUND(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO,D.DNAME
ORDER BY E.DEPTNO;

--3번
SELECT E.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.JOB,E.SAL
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO,E.ENAME;

--4번
